return {
	["algebraic geometry"]        = { "mathematics",  "algebra", "algebraic geometry", "geometry" },
	["etale"]                     = { "mathematics",  "algebra", "algebraic geometry", "geometry", "algebraic_topology", "etale", "homotopy_theory" },
	["homotopy_theory"]           = { "mathematics", "algebra", "algebraic_topology", "homotopy_theory" },
	["linear algebra"]            = { "mathematics",  "algebra", "linear_algebra" },
	["number theory (nt)"]        = { "mathematics", "algebra", "number_theory" },
	["anabelian_geometry"]        = { "mathematics", "algebra", "number_theory", "anabelian_geometry"},
	["elliptic curves"]           = { "mathematics", "algebra", "number_theory", "curves", "elliptic curves" },
	["analysis"]                  = { "mathematics", "analysis" },
	["differential geometry"]     = { "mathematics", "geometry", "differential_geometry", 'riemannian_geometry', 'sympletic geometry' },
	["complex analysis"]          = { "mathematics", "analysis", "complex_analysis" },
	["K-Theory"]                  = { "mathematics", "algebra", "analysis", "k-theory" },
	["topology"]                  = { "mathematics", "topology" },
	["algebraic topology"]        = { "mathematics", "topology", "algebra", "algebraic_topology" },
	["category theory"]           = { "mathematics", "algebra", "category_theory" },
	["probability theory"]        = { "mathematics", "probability", "statistics" },
	["PDE's"]                     = { "mathematics", "analysis", "differential_equations", "PDE" },
	["logic"]                     = { "mathematics", "foundations", "logic" },
	["set theory"]                = { "mathematics", "foundations", "set_theory" },
	["symplectic geometry"]       = { "mathematics", "geometry", "symplectic_geometry" },
	["riemannian geometry"]       = { "mathematics", "geometry", "differential_geometry", "riemannian_geometry" },
	["lie theory"]                = { "mathematics", "algebra", "differential_geometry", "lie_theory" },
	["history of mathematics"]    = { "mathematics", "history" },
	["philosophy of mathematics"] = { "mathematics", "philosophy" },
}
